platform :ios, '7.0'
pod 'Parse', '~> 1.2'
pod 'JLTMDbClient', '~> 0.2'
pod 'AFNetworking', '~> 2.3'
pod 'Mantle', '~> 1.5'
pod 'VTAcknowledgementsViewController', '~> 0.11'
pod 'ColorArt', '~> 0.1'
pod 'UICKeyChainStore', '~> 1.0'
pod 'UIAlertView+Blocks'
pod 'UIActionSheet+Blocks'