platform :ios, '7.0'
pod 'Parse', '~> 1.2.18'
pod 'JLTMDbClient', '~> 0.1.0'
pod 'AFNetworking', '~> 2.1.0'
pod 'TestFlightSDK', '~> 2.2.1-beta'
pod 'Mantle', '~> 1.3.1'
pod 'VTAcknowledgementsViewController', '~> 0.7'
pod 'ColorArt', '~> 0.1.1'
pod 'ReactiveCocoa', '~> 2.2.3'
pod 'UICKeyChainStore'
pod 'FODFormKit', '~> 0.1.1'
